LBHackney-IT/social-care-referral-form-ingestion

- google-scripts/process-form-submission/__mocks__/google_mocks.ts
- google-scripts/process-form-submission/__tests__/getProperties.test.ts
- google-scripts/process-form-submission/__tests__/main.test.ts
- google-scripts/process-form-submission/__tests__/setUniqueIdOnSubmission.test.ts
- google-scripts/process-form-submission/getProperties.ts
- google-scripts/process-form-submission/main.ts
- google-scripts/process-form-submission/setUniqueIdOnSubmission.ts
We need to be able to setup and access secrets such as the API KEY used to call the AWS S3 API Proxy.
It was suggested that we should be able to use Google's [Properties Service](https://developers.google.com/apps-script/guides/properties) to store and retrieve secrets.
From reading the documentation, it looks like adding a secret is done by calling the Properties Service API with the `setProperties` method, see [here](https://developers.google.com/apps-script/reference/properties/properties#setpropertiesproperties) and the code snippet below.
```
// Sets multiple user properties at once.
var userProperties = PropertiesService.getUserProperties();
var newProperties = {nickname: 'Bob', region: 'US', language: 'EN'};
userProperties.setProperties(newProperties);
```
If that is the case, we …
> Chore(SCT-1008): Add setup for accessing secrets in the App Script Code

- google-scripts/process-form-submission/__tests__/main.test.ts
- google-scripts/process-form-submission/main.ts
Reduce the amount of data being logged, no longer log the form data as this could be sensitive information. Just log a timestamp and error message.
> fix: Don't log sensitive data

- .circleci/config.yml
We're getting an [error](https://app.circleci.com/pipelines/github/LBHackney-IT/social-care-referral-form-ingestion/167/workflows/48471683-b67e-4953-bf1d-04ace7a87fcc/jobs/592) in the pipeline at the deploy lambda stage. Looking at the logs, it looks like some files from the Apps Script are being persisted at the point where we want to deploy the lambda.
This may not fix the above error but perhaps we want the workflow for the Apps Script code and Lambda to deploy separately. Each has their own dependencies not sure how to combine them into one job or if it's better to keep the workflows apart.
Open to suggestions, feedback, etc.
> Fix: Remove clasp push dependency for deploying lambda

- .circleci/config.yml
- referral-form-data-process/main.test.ts
- referral-form-data-process/main.ts
- referral-form-data-process/serverless.yml
This adds the following changes:
1. Format private key
This formats the private key of the service account. The reason for this is because when adding the key to the environment variables it does not format the new line characters and the auth fails.
2. Add `Promise.all`
This encapsulates the code that loops through each form data object within a Promise.all. This means that the code will wait for all the await functions to resolve before exiting the lambda. Without these, the lambda doesn't wait for the entire doc generation to finish and exits prematurely.
3. Add timeout of 30 seconds to the lambda.
The default timeout is 6 seconds. This updates it so that the lambda is up for 30 seconds before terminating itself.
> Fix(SCT-1365): Add fixes from testing lambda in test environment

- .circleci/config.yml
The job currently fails with this yarn [error](https://app.circleci.com/pipelines/github/LBHackney-IT/social-care-referral-form-ingestion/219/workflows/28062245-6d1e-4f98-8309-316c70552899/jobs/878/parallel-runs/0/steps/0-102): `@social-care-referral-form-ingestion/referral-form-data-process@1.0.0: The engine "node" is incompatible with this module. Expected version ">=14.18.0". Got "14.17.5"`
We've come across this before error and I think when we use `aws-cli/default` as the executor, the version of node it has does not match our node engine requirements.
> Fix(SCT-1489): Change executor for deploy lambda job

- .circleci/config.yml
- README.md
- google-scripts/process-form-submission/__mocks__/google_mocks.ts
- google-scripts/process-form-submission/__tests__/main.test.ts
- google-scripts/process-form-submission/__tests__/setUniqueIdOnSubmission.test.ts
- google-scripts/process-form-submission/main.ts
- google-scripts/process-form-submission/setUniqueIdOnSubmission.ts
- referral-form-data-process/lib/addGoogleDocUrlToSheet.test.ts
- referral-form-data-process/lib/addGoogleDocUrlToSheet.ts
- referral-form-data-process/main.test.ts
- referral-form-data-process/main.ts
- referral-form-data-process/serverless.yml
This PR adds a number of changes which allow a Google Doc link to be added to the spreadsheet for a form submission:
- Update the app script to send the form row of the newly added form submission to S3 along with the form data
- Add new function `addGoogleDocUrlToSheet` to be called on the lambda to update the spreadsheet with the link to a newly generated Google Doc for the respective form submission
- Add new environment variables: `URL_COLUMN` & `SPREADSHEET_ID` to the serverless and pipeline configuration.
- Update Readme
To allow members of the MASH team to access the information of a form submission on its respective Google Doc
This is the second to last step for the lambda, the last piece of work is sending the form data to our database.
> Feat(SCT-1012): Update spreadsheet with newly generated Google Doc link

- .circleci/config.yml
The role we were using does not have permissions to deploy to Mosaic Production. This updates it to use the role that will allow it to deploy to the Staging APIs account.
Based off of what we currently do for the SCCV API [here](https://github.com/LBHackney-IT/social-care-case-viewer-api/blob/e3a907a4c8e02a74122bf87624151a472862c11c/.circleci/config.yml#L26).
> Fix(SCT-1464): Change the role used for assuming the Staging role

- .circleci/config.yml
Not needed as we attach the workspace.
> Fix(SCT-1464): Remove checkout step

- .circleci/config.yml
- referral-form-data-process/serverless.yml
This adds changes to our circleCI pipeline and `serverless` config to include a Staging step for deploying the lambda.
- Updates the circleCI workflow to have steps for deploying the lambda to staging and mosaic prod
- Updates the `serverless` config so that the appropriate S3 bucket and SQS queues (depending on environment) are connected to lambda.
To Do After Merging:
- Update the environment variables to pull from AWS rather than as options in the pipeline.
> Chore(SCT-1467): Add staging pipeline for lambda

- terraform/mash-setup-staging/main.tf
We have sensitive values that the lambda needs to use to generate the google docs with the MASH form data.
This adds secret resources in AWS so that we can the lambda will have access to them.
After merging:
- Update the secrets in staging with the appropriate values
- Update `serverless` so the lambda can access the values.
> Chore(SCT-1467): Create secret manager resources for the Google credentials

- referral-form-data-process/serverless.yml
We had an error in the pipeline [here](https://app.circleci.com/pipelines/github/LBHackney-IT/social-care-referral-form-ingestion/257/workflows/439168c8-0e47-4ab3-8fa2-90baa66cfe34/jobs/1095/parallel-runs/0/steps/0-103).
This happened because we were not accessing which value we wanted (which depends on the stage).
This amends the `serverless` config to access the appropriate names of the bucket and queue depending on the environment.
> Fix(SCT-1467): Access the custom variable using the stage

- terraform/mash-setup-staging/main.tf
- terraform/modules/api-proxy-s3-sqs/secrets-for-mash-google-doc.tf
The resources couldn't access the local variable `resource_prefix` that was declared in the module folder.
This moves them into their own file within the module.
> Fix(SCT-1467): Move secret resources into module folder

- referral-form-data-process/serverless.yml
Updates the serverless config so that the lambda retrieves the values of `CLIENT_EMAIL`, `PRIVATE_KEY`, `TEMPLATE_DOCUMENT_ID` and `SPREADSHEET_ID` from AWS secrets manager.
Note:
`TITLE` and `URL_COLUMN` are not saved as secrets in AWS.
> Chore(SCT-1467): Allow lambda to access secret values for google doc generation

- terraform/modules/api-proxy-s3-sqs/secrets-for-mash-google-doc.tf
Adds terraform to create AWS resources for saving the values of the API endpoint and API key of the social care case viewer.
We POST the mash data to the SCCV API via the lambda. We need to save the endpoint and API key as environment variables the Lambda can access.
> Chore(SCT-1522): Add secrets for social care case viewer API access

- referral-form-data-process/serverless.yml
During the deploy stage, `serverless` could not find the secrets for the API endpoint and API key.
From reading, when trying to access a secret in AWS, it seems we need to add `~true` to the end of the call in the `serverless` config.
We have `~true` set up already for the other environment variables and `serverless` has not warned about these ones.
This adds `~true` to try and fix `serverless` not getting the values for the API endpoint and key.
> Fix(SCT-1522): Add `~true` to secrets manager parameter call

- .github/workflows/github-action-tag-version.yml
For us to import our MASH module into the infrastructure repo (so that we can deploy it to `Mosaic Production`), we need to pin its source repo (this repo) to a version. If we don't, the terraform linter raises an error, see [here](https://github.com/terraform-linters/tflint/blob/v0.33.1/docs/rules/terraform_module_pinned_source.md).
This introduces a Github action to add semantic versioning to our repo.
We could then reference the tag when importing our module, so that we pass this stage in linter.
> feat(SCT-1516): Add Github action to add and update the Repository tag

- .github/workflows/github-action-tag-version.yml
Uses v2 of the checkout and uses the latest version of the Github action.
> Use v2 of checkout branch and latest version of imported Github action

- terraform/mash-setup-staging/main.tf
- terraform/modules/api-proxy-s3-sqs/providers.tf
While testing that we could import the MASH module into the [infrastructure repo](https://github.com/LBHackney-IT/infrastructure/runs/4432753234?check_suite_focus=true), terraform plan printed out this warning:
```
╷
│ Warning: Provider aws is undefined
│ 
│   on 50-mash-referrals-data-import.tf line 2, in module "mash_data_processing":
│    2:   providers = { aws = aws.core }
│ 
│ Module module.mash_data_processing does not declare a provider named aws.
│ If you wish to specify a provider configuration for the module, add an
│ entry for aws in the required_providers block within the module.
╵
```
This PR moves the required providers into the module, so that we can fix this warning.
> Chore(SCT-1516): Move setup for required providers into the module

- README.md
This small PR updates the readme with a new section on manually testing the Google side of the workflow (Docs, Sheets, Form)
To make it clear to others why we will have to manually test the full MASH workflow using the staging version of each Google service
This section will likely be update to include a small bit on the staging Apps script once it has been create. I have purposely also left out any links to the Drive as I doubt we want to share that information publicly. Happy to add links if its better to include them.
> feat(SCT-1463): Update readme with new section on testing the google services manually

- referral-form-data-process/serverless.yml
We've replaced our production terraform setup to use the MASH terraform module we created.
As a result, the old production S3 bucket and SQS no longer exist and new ones have replaced them.
The names of the new resources are slightly different.
This updates the `serverless` config so that the lambda can connect to these new resources and not the old (now deleted) resources.
> Update lambda setup so that it points to the new MASH resources in production

- .circleci/config.yml
- README.md
- referral-form-data-process/lib/generateGoogleDocumentTitle.test.ts
- referral-form-data-process/lib/generateGoogleDocumentTitle.ts
- referral-form-data-process/lib/helpers/createListOfReferredClients.ts
- referral-form-data-process/lib/helpers/mapFormDataToFormDataAnswersObject.ts
- referral-form-data-process/lib/interfaces/formDataAnswers.ts
- referral-form-data-process/main.test.ts
- referral-form-data-process/main.ts
- referral-form-data-process/serverless.yml
The referral process generates a Google Document that a member of MASH would use.
We want to have each document generated to have a unique name that will help distinguish them. Currently, there is no title set so the name of the documents default to the word true
Title should follow the format:
`resident's name | service` e.g Sam Smith | MASH or if there are multiple residents, add the number of additional referrals to the first client's name e.g Sam Smith +3 | MASH
This adds a function that will grab the first client's full name from a referral, count any other residents in the referral and use the information to create a title that matches the format above.
> feat(SCT-1571): Generate Google document title based on referral submitted

- .circleci/config.yml
- README.md
- referral-form-data-process/lib/generateGoogleDocumentTitle.test.ts
- referral-form-data-process/lib/generateGoogleDocumentTitle.ts
- referral-form-data-process/lib/helpers/createListOfReferredClients.ts
- referral-form-data-process/lib/helpers/mapFormDataToFormDataAnswersObject.ts
- referral-form-data-process/lib/interfaces/formDataAnswers.ts
- referral-form-data-process/lib/sendDataToAPI.ts
- referral-form-data-process/main.test.ts
- referral-form-data-process/main.ts
- referral-form-data-process/serverless.yml
The referral process generates a Google Document that a member of MASH would use.
This happens once the MASH form is submitted.
Depending on the number of other people in a submitted referral, this will generate a title for the generated google doc.
For the changes in #66 we copied the code used in the `sendDataToAPI` file to map the form data into an object and we introduced two new folders:
- helpers
- interfaces
Since the original code was copied from the `sendDataToAPI` file, in this commit, we refactor this file to import these functions as well.
> Refactor `sendDataToApi` to use extracted methods

- referral-form-data-process/lib/helpers/createListOfReferredClients.ts
- referral-form-data-process/lib/helpers/mapFormDataToFormDataAnswersObject.ts
- referral-form-data-process/lib/interfaces/formDataAnswers.ts
In the build pipeline, when we compile the lambda we get an error: `error TS2304: Cannot find name 'FormDataAnswersObject'.`
This commit exports the interface so that the interface can be found during compiling.
> fix(SCT-1571): Export interface to fix typescript compile error

- .circleci/config.yml
This repo will not be actively maintained so removing the infrastructure that was set up using the pipeline. 
Follow up PR to update the README to follow after.
> Update pipeline to remove terraform and lambda resources

- .circleci/config.yml
- README.md
- google-scripts/package.json
- google-scripts/yarn.lock
- referral-form-data-process/package.json
- referral-form-data-process/yarn.lock
Since we are no longer continuing with the MASH work, this repo will not be actively maintained.
This:
- Updates the readme to explain this
- Updates the pipeline to only run tests and not deploy
- Updates all installed packages
> Set Repo as deprecated
